### ISSUE TITLE
Add support for custom model data

### ISSUE THREAD

**Issue by Funasitien** [devblook/akropolis#12]
### Is your feature request related to a problem?

Could you add custom model data support into menu and join item ?

### Describe the solution you'd like

add a custommodel atibute like:

```yaml
  items:
    infobook:
      material: BOOK
      amount: 1
      slot: 0
      model: 1010 # Add this
      display_name: "<gold>Server Information <gray>(Right-Click)"
      lore:
        - "<dark_gray>» <gray>Right click to see information about the server!"
```

### Describe alternatives you've considered

idk
